FROM golang:1.21-bookworm AS builder
WORKDIR /app
COPY api-gateway/ ./
RUN go mod tidy
RUN go test ./pkg/... ./internal/... -v

FROM scratch
COPY --from=builder /app/server /server
EXPOSE 8080
ENTRYPOINT ["/server"]
